apiVersion: v1
kind: Pod
metadata:
  name: two-container-pod
  labels:
    app: myapp
spec:
  containers:
    - name: nginx-container
      image: nginx
      ports:
        - containerPort: 80
      resources:
        requests:
          cpu: 500m
          memory: 200Mi
        limits:
          cpu: 1Gi
          memory: 500Mi
    - name: redis-container
      image: redis
      resources:
        requests:
          cpu: 500m
          memory: 200Mi
        limits:
          cpu: 1Gi
          memory: 500Mi
