name: TEST ACTION

on:
  workflow_dispatch:
    paths:
      - '**.yaml'  # Filter workflow to only run if a .yaml file is changed

env:
  PROJECT_ID: 'github-action-393418'
  PROJECT_NUMBER: '168241442549'
  
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - uses: actions/checkout@v3

    - id: 'auth'
      name: 'Obtain access token by using workload identity federation'
      uses: 'google-github-actions/auth@v1'
      with:
        workload_identity_provider: projects/${{ env.PROJECT_NUMBER }}/locations/global/workloadIdentityPools/github-actions/providers/github-actions-oidc
        service_account: github-actions-workflow@${{ env.PROJECT_ID }}.iam.gserviceaccount.com

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'

    - name: 'Set up Python'
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        pip install google-cloud-bigquery octokit yaml

    - name: Check yaml files and query BigQuery
      run: |
        python .github/scripts/check_yaml_bigquery.py

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: Update Kubernetes resources
        title: Update Kubernetes resources
        branch: update-resources
        body: Updated Kubernetes resources from BigQuery
