name: BigQuery Data Fetch

on:
  push:
    branches:
      - main

jobs:
  bigquery-fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Google Cloud authentication
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

      - name: Fetch BigQuery data
        id: bigquery
        uses: docker://google/cloud-sdk:latest
        with:
          entrypoint: /bin/bash
          args: |
            -c "echo 'Authenticating with Google Cloud...'
            gcloud auth activate-service-account --key-file <(echo '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}')
            echo 'Fetching data from BigQuery...'
            bq query --nouse_legacy_sql --format=json 'SELECT * FROM github-action-393418.test.test'"
        
      - name: Print BigQuery Data
        run: echo "${{ steps.bigquery.outputs.stdout }}"
