name: NEW

on:
  workflow_dispatch:

env:
  PROJECT_ID: 'github-action-393418'
  PROJECT_NUMBER: '168241442549'
  
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    # actions/checkout MUST come before auth
    - uses: 'actions/checkout@v3'
    
    
    
    #- name: Get K8 Kind
     # uses: 'mikefarah/yq@master'
     # with:
     #   run: ./manifests/test-jq.sh
      #  cmd: yq '.kind' "manifests/pod.yaml"

    #
    # Authenticate to Google Cloud using workload identity federation
    #
    - id: 'auth'
      name: 'Obtain access token by using workload identity federation'
      uses: 'google-github-actions/auth@v1'
      with:
        workload_identity_provider: projects/${{ env.PROJECT_NUMBER }}/locations/global/workloadIdentityPools/github-actions/providers/github-actions-oidc
        service_account: github-actions-workflow@${{ env.PROJECT_ID }}.iam.gserviceaccount.com
        
    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'

    - name: 'Use gcloud CLI'
      run: |
          gcloud config set project ${{ env.PROJECT_ID }}
    
    - name: 'TEST RESULT'
      run: bq query --nouse_legacy_sql --format=json 'SELECT CAST(cpu_requested_recommendation AS INT64) AS cpu_requested_recommendation FROM `github-action-393418.data.container_recommendations` LIMIT 1' | jq -r '.[0].cpu_requested_recommendation'
     
    - name: 'Loop through files, perform BigQuery, and update yaml files'
      run: |
        shopt -s globstar nullglob
        for file in ./manifests/*.yaml; do
          cpu=$(yq e '.spec.template.spec.containers[0].resources.requests.cpu' "$file")
          memory=$(yq e '.spec.template.spec.containers[0].resources.requests.memory' "$file")
          echo "Existing CPU: $cpu, Memory: $memory"
          
          cpu_new=$(bq query --nouse_legacy_sql --format=json 'SELECT CAST(cpu_requested_recommendation AS INT64) AS cpu_requested_recommendation FROM `github-action-393418.data.container_recommendations` LIMIT 1' | jq -r '.[0].cpu_requested_recommendation')
          echo "********************"
          echo cpu_new
          echo "********************"
          
          yq e -i ".spec.template.spec.containers[0].resources.requests.cpu = \"$cpu_new\"" "$file"
        done
    
    - name: 'Create new branch, commit and push changes'
      run: |
        git config --global user.email "ameenah.burhan@gmail.com
        git config --global user.name "GitHub Action"
        git checkout -b updated-yaml-files
        git add -A
        git commit -m "Updated YAML files with new CPU and memory values"
        git push origin updated-yaml-files

    - name: 'Create Pull Request'
      uses: 'peter-evans/create-pull-request@v3'
      with:
        title: 'Updated YAML files with new CPU and memory values'
        body: 'This PR updates the CPU and memory values in all YAML files'
        branch: 'updated-yaml-files'
    #- name: 'Use gcloud CLI'
     # run: bq query --use_legacy_sql=false 'SELECT * FROM `github-action-393418.test.test`'

      
    #- name: Set up Python
    #  uses: actions/setup-python@v4
    #  with:
    #    python-version: 3.9

    #- name: Install dependencies
    #  run: pip install google-cloud-bigquery

    #- name: Run script
    #  run: python main-chat.py
    
