name: Fetch BigQuery Data 2

on:
  workflow_dispatch:

env:
  PROJECT_ID: 'github-action-393418'
  PROJECT_NUMBER: '168241442549'
  
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    # actions/checkout MUST come before auth
    - uses: 'actions/checkout@v3'

    - name: Set foobar to cool
      uses: mikefarah/yq@master
      with:
        cmd: yq -i '.foo.bar = "cool"' 'config.yml'
    - name: Get an entry with a variable that might contain dots or spaces
      id: get_username
      uses: mikefarah/yq@master
      with:
        cmd: yq '.all.children.["${{ matrix.ip_address }}"].username' ops/inventories/production.yml
    - name: Reuse a variable obtained in another step
      run: echo ${{ steps.get_username.outputs.result }}
    #
    # Authenticate to Google Cloud using workload identity federation
    #
    - id: 'auth'
      name: 'Obtain access token by using workload identity federation'
      uses: 'google-github-actions/auth@v1'
      with:
        workload_identity_provider: projects/${{ env.PROJECT_NUMBER }}/locations/global/workloadIdentityPools/github-actions/providers/github-actions-oidc
        service_account: github-actions-workflow@${{ env.PROJECT_ID }}.iam.gserviceaccount.com
        
    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'

    - name: 'Use gcloud CLI'
      run: bq query --use_legacy_sql=false 'SELECT * FROM `github-action-393418.test.test`'

      
    #- name: Set up Python
    #  uses: actions/setup-python@v4
    #  with:
    #    python-version: 3.9

    #- name: Install dependencies
    #  run: pip install google-cloud-bigquery

    #- name: Run script
    #  run: python main-chat.py
    
