name: NEW

on:
  workflow_dispatch:

env:
  PROJECT_ID: 'github-action-393418'
  PROJECT_NUMBER: '168241442549'
  
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    # actions/checkout MUST come before auth
    - uses: 'actions/checkout@v3'
    
    
    
    - name: Get K8 Kind
      uses: 'mikefarah/yq@master'
      with:
        run: ./manifests/test-jq.sh
        cmd: yq '.kind' "manifests/pod.yaml"

    #
    # Authenticate to Google Cloud using workload identity federation
    #
    - id: 'auth'
      name: 'Obtain access token by using workload identity federation'
      uses: 'google-github-actions/auth@v1'
      with:
        workload_identity_provider: projects/${{ env.PROJECT_NUMBER }}/locations/global/workloadIdentityPools/github-actions/providers/github-actions-oidc
        service_account: github-actions-workflow@${{ env.PROJECT_ID }}.iam.gserviceaccount.com
        
    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'

    #- name: 'Use gcloud CLI'
      #run: |
          #gcloud config set project ${{ env.PROJECT_ID }}
    
    - name: 'Get workload recommendation'
      id: bigquery
      run: |
       bq query --nouse_legacy_sql --format=json 'SELECT CAST(cpu_requested_recommendation AS INT64) AS cpu_requested_recommendation FROM `github-action-393418.data.container_recommendations` LIMIT 1'
       export CPU=$(bq query --nouse_legacy_sql --format=json 'SELECT CAST(cpu_requested_recommendation AS INT64) AS cpu_requested_recommendation FROM `github-action-393418.data.container_recommendations` LIMIT 1'| jq -r '.[0].cpu_requested_recommendation')
       echo $CPU
       
    - name: Get K8 Kind
      uses: 'mikefarah/yq@master'
      with: 
       cmd: |
        yq eval -i '.spec.containers[0].resources.requests.cpu = "${{ steps.bigquery.outputs.CPU }}"' manifests/pod.yaml

    - uses: actions/checkout@v2
    - uses: actions/update-file@v1
      with:
        path: README.md
        text: This is a new README file.
    - uses: actions/create-pull-request@v1
      with:
        title: Update README file
        body: This pull request updates the README file. 
    #cmd: yq '.kind' "manifests/pod.yaml"    
  
    #- name: 'Create Pull Request'
     # uses: 'peter-evans/create-pull-request@v3'
     # with:
      #  title: 'Updated YAML files with new CPU and memory values'
      #  body: 'This PR updates the CPU and memory values in all YAML files'
      #  branch: 'updated-yaml-files'
    #- name: 'Use gcloud CLI'
     # run: bq query --use_legacy_sql=false 'SELECT * FROM `github-action-393418.test.test`'

      
    #- name: Set up Python
    #  uses: actions/setup-python@v4
    #  with:
    #    python-version: 3.9

    #- name: Install dependencies
    #  run: pip install google-cloud-bigquery

    #- name: Run script
    #  run: python main-chat.py
    
